#services
services:
    monolog.formatter.bilna.format:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%context%% %%channel%%.%%level_name%%: %%message%%\n"
#     monolog.formatter.line_applog_info:
#         class: Monolog\Formatter\LineFormatter
#         arguments:
#             - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"
#         # tags:
#         #      - { name: monolog.logger, channel: shipmentinfo }
#     # applog.services:
#     #     tags:
#     #         - { name: monolog.logger, channel: appx}
    # monolog.processor.format_logger:
    #     class: Acme\DemoBundle\FormatLoggerProcessor
    #     #arguments:  ["@session"]
    #     tags:
    #         - { name: monolog.processor, method: processRecord }

#monolog
monolog:
    channels: ["apierror", "apiinfo", "dberror", "dbinfo", "paymenterror", "paymentinfo", "syserror", "sysinfo"]
    handlers:
        main:
            type: stream
            path: "%kernel.root_dir%/logs/applog_%kernel.environment%_error.log"
            channels: ["!apierr", "!apiinfo"]
        apierror:
            type: rotating_file
            path: "%kernel.root_dir%/logs/api/error/api_%kernel.environment%.log"
            level: error
            formatter: monolog.formatter.bilna.format
            channels: [apierror]
        apiinfo:
            type: rotating_file
            path: "%kernel.root_dir%/logs/api/info/api_%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.bilna.format
            channels: [apiinfo]
        dberror:
            type: rotating_file
            path: "%kernel.root_dir%/logs/db/error/db_%kernel.environment%.log"
            level: error
            formatter: monolog.formatter.bilna.format
            channels: [dberror]
        dbinfo:
            type: rotating_file
            path: "%kernel.root_dir%/logs/db/info/db_%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.bilna.format
            channels: [dbinfo]
        paymenterror:
            type: rotating_file
            path: "%kernel.root_dir%/logs/payment/error/payment_%kernel.environment%.log"
            level: error
            formatter: monolog.formatter.bilna.format
            channels: [paymenterror]
        paymentinfo:
            type: rotating_file
            path: "%kernel.root_dir%/logs/payment/info/payment_%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.bilna.format
            channels: [paymentinfo]
        syserror:
            type: rotating_file
            path: "%kernel.root_dir%/logs/sys/error/sys_%kernel.environment%.log"
            level: error
            formatter: monolog.formatter.bilna.format
            channels: [syserror]
        sysinfo:
            type: rotating_file
            path: "%kernel.root_dir%/logs/sys/info/sys_%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.bilna.format
            channels: [sysinfo]